name: Label issues and pull requests
on:
  issues:
    types:
      - reopened
      - opened
  pull_request:
    types:
      - reopened
      - opened
jobs:
  label_issues_and_prs:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const isIssue = !!context.payload.issue;
            const number = isIssue ? context.issue.number : context.payload.pull_request.number;

            github.rest.issues.addLabels({
              issue_number: number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["triage"]
            })